#! /bin/sh


###################################
#====START UP SCRIPTS/PROGRAMS====#
###################################
#$HOME/.config/bspwm/startups/autostart.sh
usrpolybar &

###############
#====SXHKD====#
###############

pgrep -x sxhkd > /dev/null || sxhkd &


###############
#====BSPWM====#
###############

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Configurations
bspc config border_width			1
bspc config window_gap				10
bspc config split_ratio				0.55
bspc config top_padding				0
bspc config bottom_padding			0
bspc config right_padding			0
bspc config left_padding			0	
bspc config borderless_monocle		false
bspc config gapless_monocle			false
bspc config presel_feedback			true
bspc config focus_follows_pointer	false

# Colors
bspc config normal_border_color 	\#5886b0
bspc config focused_border_color	\#c5dcf1
bspc config presel_feedback_color	\#373B41


###################
#====BSPC RULES===#
###################

bspc rule -a Lxappearance state=floating
bspc rule -a Tk state=floating
bspc rule -a Nm-connection-editor state=floating
