#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d				1 2 3 4 5
bspc monitor HDMI-2 -d				6 7 8 9 0

bspc config border_width			1
bspc config window_gap				8

bspc config -m DP-1 top_padding			35
bspc config -m DP-1 bottom_padding		1

bspc config -m HDMI-2 top_padding		35
bspc config -m HDMI-2 bottom_padding		28

bspc config split_ratio				0.5
bspc config borderless_monocle			true
bspc config gapless_monocle			false
bspc config normal_border_color			\#0D1826
bspc config focused_border_color		\#517C8C
bspc config active_border_color			\#C5C8C6
bspc config presel_feedback_color		\#254559
bspc config focus_follows_pointer		true

bspc rule -a Nitrogen state=floating
bspc rule -a Code desktop=^6 follow=on
