#! /bin/sh


#====SXHKD====#
pgrep -x sxhkd > /dev/null || sxhkd &


#====START UP SCRIPTS====#
$HOME/.config/bspwm/autostart

#====BSPWM====#
# Monitor
bspc monitor HDMI-2 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

# Config
bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio	0.5
bspc config borderless_monocle true
bspc config gapless_monocle	true	
bspc config focused_border_color \#ffffff
bspc config active_border_color	\#223543
bspc config presel_feedback_color \#254559
bspc config focus_follows_pointer false


#====RULES====#
bspc rule -a Nitrogen state=floating
bspc rule -a Nm-connection-editor state=floating
