#! /bin/sh


###################################
#====START UP SCRIPTS/PROGRAMS====#
###################################
$HOME/.config/bspwm/startups/autostart.sh
# usrpolybar &

###############
#====SXHKD====#
###############

pgrep -x sxhkd > /dev/null || sxhkd &


###############
#====BSPWM====#
###############

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Configurations
bspc config border_width      2
bspc config window_gap        10
bspc config split_ratio       0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config presel_feedback     true
bspc config focus_follows_pointer false

# Colors
bspc config normal_border_color   \#5886b0
bspc config focused_border_color  \#c5dcf1
bspc config presel_feedback_color \#373B41


###################
#====BSPC RULES===#
###################

bspc rule -a Lxappearance state=floating
bspc rule -a Nm-connection-editor state=floating
