#!/usr/bin/bash

# this script dims both monitor by a certain value

dimVal=0.3 # Adjusting this value right here for the default dim-ness(?)
ERROR="Available options are:\n		-r to reset\n		-d to dim"

dim () {
	xrandr --output $1 --brightness $dimVal
}

function reset {
	xrandr --output HDMI-2 --brightness 1
	xrandr --output DP-1 --brightness 1
}


case $1 in
	"-d")
		dim HDMI-2; dim DP-1
		;;
	"-r")
		reset
		;;
	*)
		echo -e $ERROR 
		;;
esac
