#!/usr/bin/python3

# Check on time and set dim screen corresponding to it

from datetime import datetime 
from datetime import time
import os 

def get_time():
    """Return time in hour, minute"""
    time_now = datetime.now()
    time_now = time_now.strftime("%H:%M")
    time = time_now.split(":")
    return time[0], time [1]
    
def compare_time():
    """Function return a signal if current time is between 9:30pm and 5:30am"""
    hour, minute = get_time() 
    current_time = time(
            hour = int(hour),
            minute = int(minute)
        )
    time_am = time(hour=6, minute=0)
    time_pm = time(hour=22, minute=30)
    if current_time > time_pm or current_time < time_am:
        return True
    else:
        return False
 

if __name__ == "__main__":
    is_late = compare_time() # bool = True is late, bool = Flase is not late
    cmd = ['dim -d', 'usrredshift'] # dim the screen, turns on redshift
    if is_late:
        for command in cmd:
            os.system(command)
    
