#!/usr/bin/python3

import sys, os

target_dir = {
    "1": "Movies",
    "2": "Shows",
}

def main():
    filenames = " ".join([f"'{i}'" for i in sys.argv[1:]])

    print("1. Movie\n2. Show")
    choice = input("Enter file type: ")

    cmd = f"scp -r {filenames} nas:/home/haln/media/{target_dir[choice]} && rm -r {filenames}"

    os.system(cmd)

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"failed to execute:\n{e}")
