[general]
import = [
  "/home/haln/Repositories/dotfiles/.config/alacritty/themes/one_dark.toml",
]

[scrolling]
history = 100000
multiplier = 2

[window]
decorations = "full"

[window.dimensions]
columns = 130
lines = 38

[window.position]
x = 54
y = 44

[window.padding]
x = 4
y = 4

[font]
normal = { family = "MonaspiceAr Nerd Font Mono", style = "Regular" }
size = 12.5
