#!/usr/bin/bash

FILE_PATH=$HOME/.ssh-hosts

if [ ! -f "${FILE_PATH}" ];then
    echo "${FILE_PATH} not found.
Make sure this file exists and the content is of the format
\`user@ip some description\`"
    exit 1
fi
SSH_ADDR=$(cat $FILE_PATH | fzf | awk '{ print $1 }')
[ -z "${SSH_ADDR}" ] || alacritty -T "ssh://${SSH_ADDR}" -e ssh ${SSH_ADDR} &
